name: Deploy front-end and back-end code to Docker Hub

# Déclenchement quand les workflows d’analyse sont terminés
on:
  workflow_run:
    workflows: 
      - "Run back-end tests and Sonar analysis"
      - "Test and analyse front-end code"
    types:
      - completed

jobs:
  deploy-frontend:
    name: Deploy frontend image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'Test and analyse front-end code' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: front
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

  deploy-backend:
    name: Deploy backend image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'Run back-end tests and Sonar analysis' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: back
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
