name: Deploy back-end code to docker hub 

# The workflow is triggered when the back-end code analysis is completed
on:
  workflow_run:
    workflows: ["Analyse back-end code"]
    types:
      - completed
            
jobs:

  docker:
  
    name: Deploy docker image
    runs-on: ubuntu-latest
    
    steps:

      # Checkout to code 
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setups
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Push docker image to docker hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: back
          # Use the dockerfile
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
