name: Deploy front-end code to docker hub

# The workflow is triggered when the analysis of the front-end code is completed
on:
  workflow_run:
    workflows: ["Analyse front-end code"]
    types:
      - completed
            
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # Checkout to code
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to docker hub 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Setups
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Push image on docker hub
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: front
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
