name: Run back-end tests

on:
    # Trigger the workflow on push for the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Set up Java version
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'

            # Run tests
            # ALTERNATIVE VERSION --> Verify that the project builds correctly and run tests
            - name: Build with Maven
              working-directory: back
              run: mvn clean test
              # ALTERNATIVE VERSION --> run: mvn -B package --file pom.xml

            # Generate Jacoco test report
            - name: Generate Jacoco coverage report
              working-directory: back
              run: mvn jacoco:report
              # ALTERNATIVE VERSION --> run: mvn -B verify
              
            # Upload the coverage report
            - name: Upload Jacoco coverage report
              uses: actions/upload-artifact@v4
              with:
                name: jacoco-report
                path: back/target/site/jacoco
