name: Analyse front-end code

# The workflow is triggered when front-end tests job is completed 
on:
  workflow_run:
    workflows: ["Run front-end tests"]
    types:
      - completed

jobs:

  sonarqube:

    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      # Checkout to code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #- name: Télécharger tous les artifacts disponibles
        #uses: actions/download-artifact@v4

      #- name: Vérifier où les artifacts ont été téléchargés
        #run: ls -R ${{ github.workspace }}

      - name: Télécharger les résultats de coverage dans un dossier temporaire
        uses: actions/download-artifact@v4
        with:
          name: frontend-test-results
          path: downloaded-artifacts

      - name: Vérifier le contenu de l'artifact téléchargé
        run: ls -R downloaded-artifacts


      - name: Télécharger les résultats de coverage
        uses: actions/download-artifact@v4
        with:
          name: frontend-test-results
          path: ${{ github.workspace }}/front/coverage/bobapp

      - name: Vérifier l'existence du fichier de coverage
        run: ls -l front/coverage/bobapp/

      # Code analysis 
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
            -Dsonar.sources=src
            -Dsonar.inclusions=src/**/*.ts
            -Dsonar.exclusions=**/*.spec.ts,**/test.ts
