name: Analyse front-end code

# The workflow is triggered when front-end tests job is completed
on:
  workflow_run:
    workflows: ["Run front-end tests"]
    types:
      - completed
    
jobs:

  sonarqube:
  
    name: SonarQube
    runs-on: ubuntu-latest
    
    steps:
      # Checkout to code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check lcov file content
        run: cat front/coverage/bobapp/lcov.info || echo "lcov.info not found"

      # Code analysis 
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
            -Dsonar.sources=src
            -Dsonar.inclusions=src/**/*.ts
            -Dsonar.exclusions=**/*.spec.ts,**/test.ts
