name: Run back-end tests and Sonar analysis

on:
    # Trigger the workflow on push for the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Set up Java version
            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                java-version: '11'
                distribution: 'temurin'

            # Run tests
            - name: Build with Maven
              working-directory: back
              run: mvn clean test

            # Generate Jacoco test report
            - name: Generate Jacoco coverage report
              working-directory: back
              run: mvn jacoco:report
              
            # Upload the coverage report
            - name: Upload Jacoco coverage report
              uses: actions/upload-artifact@v4
              with:
                name: jacoco-report
                path: back/target/site/jacoco

            # Caching
            - name: Cache SonarQube packages
              uses: actions/cache@v4
              with:
                  path: ~/.sonar/cache
                  key: ${{ runner.os }}-sonar
                  restore-keys: ${{ runner.os }}-sonar
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
          
            # Run code analysis
            - name: Build and analyze
              working-directory: back
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
              run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=JoPrignol_OC-Project-10-BACK
