name: Test and analyse front-end code

on:
    # Trigger the workflow on push for the main branch
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:

  sonarqube:

    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      # Checkout to code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Build project
      - name: Install dependencies
        working-directory: front
        run: npm ci

      # Run tests
      - name: Run tests
        working-directory: front
        run: npm run test:prod

      # verify that the coverage files exist
      - name: check for coverage files
        run: ls -l front/coverage/bobapp/

      # Upload front-end tests results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: front/coverage
          retention-days: 1

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: frontend-test-results
          path: ${{ github.workspace }}/front/coverage/bobapp

      # Verify that the coverage files exist
      - name: check for coverage files
        run: ls -l front/coverage/bobapp/

      # Code analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
            -Dsonar.sources=src
            -Dsonar.inclusions=src/**/*.ts
            -Dsonar.exclusions=**/*.spec.ts,**/test.ts
